# Generated by Django 4.1.3 on 2022-12-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listingRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_name', models.CharField(default='', max_length=30)),
                ('listing_contact', models.CharField(default='', max_length=20)),
                ('listing_email', models.CharField(default='', max_length=30)),
                ('listing_eir', models.CharField(default='', max_length=30)),
                ('listing_latitude', models.CharField(default='', max_length=20)),
                ('listing_longitude', models.CharField(default='', max_length=20)),
                ('listing_available_from', models.DateField(auto_now=True)),
                ('listing_available_to', models.DateField(auto_now=True)),
                ('listing_address', models.CharField(default='', max_length=50)),
                ('listing_rent', models.IntegerField(default=0)),
                ('listing_deposite', models.IntegerField(default=0)),
                ('listing_is_bill_included', models.BooleanField(default=False, null=True)),
                ('listing_no_of_bedrooms', models.IntegerField(default=0)),
                ('listing_no_of_bathrooms', models.IntegerField(default=0)),
                ('listing_ensuite_no', models.IntegerField(default=0)),
                ('listing_single_bed', models.BooleanField(default=False, null=True)),
                ('listing_twin_share', models.BooleanField(default=False, null=True)),
                ('listing_single_room', models.BooleanField(default=False, null=True)),
                ('listing_male_preferred', models.BooleanField(default=False, null=True)),
                ('listing_female_preferred', models.BooleanField(default=False, null=True)),
                ('listing_couple_preferred', models.BooleanField(default=False, null=True)),
                ('listing_student_preferred', models.BooleanField(default=False, null=True)),
                ('listing_working_preferred', models.BooleanField(default=False, null=True)),
                ('listing_tv_available', models.BooleanField(default=False, null=True)),
                ('listing_wifi_available', models.BooleanField(default=False, null=True)),
                ('listing_washing_available', models.BooleanField(default=False, null=True)),
                ('listing_table_available', models.BooleanField(default=False, null=True)),
                ('listing_wardrobe_available', models.BooleanField(default=False, null=True)),
                ('listing_additional_text', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
