# Generated by Django 4.1.3 on 2022-12-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingraw',
            name='listing_available_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='listingraw',
            name='listing_available_to',
            field=models.DateField(),
        ),
    ]
