# Generated by Django 4.1.3 on 2022-12-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingraw',
            name='listing_is_bill_included',
            field=models.BooleanField(default=True),
        ),
    ]
