# Generated by Django 4.1.3 on 2022-12-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homie', '0002_listingraw_listing_is_bill_included'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingraw',
            name='listing_is_bill_included',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
