# Generated by Django 4.1.3 on 2022-12-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homie', '0003_alter_listingraw_listing_is_bill_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingraw',
            name='listing_additional_text',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='listingraw',
            name='listing_address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='listingraw',
            name='listing_available_from',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='listingraw',
            name='listing_available_to',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='listingraw',
            name='listing_couple_preferred',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='listingraw',
            name='listing_deposite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listingraw',
            name='listing_eir',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='listingraw',
            name='listing_email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='listingraw',
            name='listing_ensuite_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listingraw',
            name='listing_female_preferred',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='listingraw',
            name='listing_male_preferred',
            field=models.BooleanField(default=0, null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='listingraw',
            name='listing_no_of_bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listingraw',
            name='listing_no_of_bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listingraw',
            name='listing_rent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listingraw',
            name='listing_single_bed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='listingraw',
            name='listing_single_room',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='listingraw',
            name='listing_student_preferred',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='listingraw',
            name='listing_table_available',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='listingraw',
            name='listing_tv_available',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='listingraw',
            name='listing_twin_share',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='listingraw',
            name='listing_wardrobe_available',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='listingraw',
            name='listing_washing_available',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='listingraw',
            name='listing_wifi_available',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='listingraw',
            name='listing_working_preferred',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='listingraw',
            name='listing_contact',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='listingraw',
            name='listing_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
