# Generated by Django 4.1.3 on 2022-12-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homie', '0006_alter_listingraw_listing_couple_preferred_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingraw',
            name='listing_couple_preferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listingraw',
            name='listing_female_preferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listingraw',
            name='listing_is_bill_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listingraw',
            name='listing_male_preferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listingraw',
            name='listing_single_bed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listingraw',
            name='listing_single_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listingraw',
            name='listing_student_preferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listingraw',
            name='listing_table_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listingraw',
            name='listing_tv_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listingraw',
            name='listing_twin_share',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listingraw',
            name='listing_wardrobe_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listingraw',
            name='listing_washing_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listingraw',
            name='listing_wifi_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listingraw',
            name='listing_working_preferred',
            field=models.BooleanField(default=False),
        ),
    ]
