# Generated by Django 4.1.3 on 2022-12-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homie', '0007_listingraw_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingraw',
            name='listing_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
