# Generated by Django 4.1.3 on 2022-12-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homie', '0008_alter_listingraw_listing_couple_preferred_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingraw',
            name='listing_latitude',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='listingraw',
            name='listing_longitude',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='listingraw',
            name='listing_contact',
            field=models.CharField(default='', max_length=20),
        ),
    ]
