# Generated by Django 4.1.3 on 2022-12-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homie', '0009_logindetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindetails',
            name='agent_contact',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='logindetails',
            name='agent_email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='logindetails',
            name='agent_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
