# Generated by Django 4.1.3 on 2022-12-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homie', '0010_logindetails_agent_contact_logindetails_agent_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(default='', max_length=50)),
                ('property_id', models.CharField(default='', max_length=50)),
                ('eir_code', models.CharField(default='', max_length=30)),
                ('rent', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=50)),
                ('no_of_bedroom', models.IntegerField(default=0)),
            ],
        ),
    ]
