# Generated by Django 4.1.3 on 2022-12-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homie', '0011_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='mappings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eir_code', models.CharField(default='', max_length=30)),
                ('latitude', models.CharField(default='', max_length=20)),
                ('longitude', models.CharField(default='', max_length=20)),
                ('responseJSON', models.CharField(default='', max_length=400)),
                ('isAvailable', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
