# Generated by Django 4.1.3 on 2022-12-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homie', '0013_alter_mappings_responsejson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappings',
            name='responseJSON',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
