# Generated by Django 4.1.3 on 2022-12-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homie', '0014_alter_mappings_responsejson'),
    ]

    operations = [
        migrations.CreateModel(
            name='propertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(default='', max_length=50)),
                ('property_cost_id', models.CharField(default='', max_length=50)),
                ('property_availability_id', models.CharField(default='', max_length=50)),
                ('property_rooms_id', models.CharField(default='', max_length=50)),
                ('property_preference_id', models.CharField(default='', max_length=50)),
                ('property_amenities_id', models.CharField(default='', max_length=50)),
                ('property_info_id', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
