# Generated by Django 4.1.3 on 2022-12-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homie', '0015_propertydetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='aminitiesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_amenities_id', models.CharField(default='', max_length=50)),
                ('tv_available', models.BooleanField(default=False, null=True)),
                ('table_available', models.BooleanField(default=False, null=True)),
                ('wardrobe_available', models.BooleanField(default=False, null=True)),
                ('washing_available', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='extraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_info_id', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('additional_info', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='preferenceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_preference_id', models.CharField(default='', max_length=50)),
                ('male_pref', models.BooleanField(default=False, null=True)),
                ('female_pref', models.BooleanField(default=False, null=True)),
                ('couple_pref', models.BooleanField(default=False, null=True)),
                ('student_pref', models.BooleanField(default=False, null=True)),
                ('working_pref', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='propertyAvailabilityDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_availability_id', models.CharField(default='', max_length=50)),
                ('availableFrom', models.DateField()),
                ('availableTill', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='propertyBedroomInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedroom_id', models.BooleanField(default=False, null=True)),
                ('no_of_bedrooms', models.IntegerField(default=0)),
                ('single_bed', models.BooleanField(default=False, null=True)),
                ('double_bed', models.BooleanField(default=False, null=True)),
                ('twin_share', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='propertyCostingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_cost_id', models.CharField(default='', max_length=50)),
                ('rent', models.IntegerField(default=0)),
                ('deposite', models.IntegerField(default=0)),
                ('billsIncluded', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='propertyRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_rooms_id', models.CharField(default='', max_length=50)),
                ('bedroom_id', models.CharField(default='', max_length=50)),
                ('no_of_bathrooms', models.IntegerField(default=0)),
                ('ensuite_no', models.IntegerField(default=0)),
            ],
        ),
    ]
